export const PERSONAL_INFO = {
  name: 'Sanjai',
  fullName: 'Sanjai G',
  role: 'Web Designer & Developer',
  tagline: 'I build websites that grow your business.',
  location: 'Salem, Tamil Nadu, India',
  email: 'sanjai.sparkmail@gmail.com',
  whatsapp: '919363265552',
  github: 'https://github.com/Sanjai-Gopal',
  linkedin: 'https://www.linkedin.com/in/sanjai2306',
  instagram: 'https://instagram.com/hey.sanjai_',
  bio: 'I design and build fast, beautiful websites for businesses — restaurants, salons, real estate, and more. From idea to launch, I handle everything so you can focus on running your business.',
};

export const STATS = [
  { value: '15+', label: 'Projects Delivered' },
  { value: '100%', label: 'Client Satisfaction' },
  { value: '7 Days', label: 'Avg. Delivery Time' },
  { value: '24/7', label: 'Support Available' },
];

export const SERVICES = [
  {
    icon: 'Monitor',
    title: 'Business Website',
    description: 'A clean, fast, mobile-friendly website that represents your brand perfectly and brings in customers.',
    features: ['Custom Design', 'Mobile Responsive', 'SEO Ready', 'Contact Form'],
    price: '₹4,999',
    accent: '#00e5ff',
    popular: false,
  },
  {
    icon: 'Zap',
    title: 'Landing Page',
    description: 'A high-converting single page built to turn visitors into leads — perfect for offers, launches, and ads.',
    features: ['Conversion Focused', 'Fast Loading', 'WhatsApp Integration', 'Analytics Ready'],
    price: '₹2,999',
    accent: '#7c3aed',
    popular: true,
  },
  {
    icon: 'ShoppingBag',
    title: 'Online Store',
    description: 'Start selling online with a professional e-commerce store — product listings, payments, and delivery.',
    features: ['Product Catalog', 'Payment Gateway', 'Order Management', 'Mobile App Ready'],
    price: '₹9,999',
    accent: '#39ff14',
    popular: false,
  },
];

export const PROJECTS = [
  {
    id: 'p1',
    title: 'Sanjai Restaurant',
    category: 'Restaurant',
    description: 'Full website with menu, gallery, and online table booking system. Increased walk-ins by 40% in the first month.',
    tags: ['React', 'Tailwind', 'Node.js'],
    image: 'sanjai_restaurant_3d_1779609123912.jpg',
    result: '+40% Walk-ins',
    accent: '#ff6b6b',
    liveUrl: '#',
  },
  {
    id: 'p2',
    title: 'Noir Elite Barbershop',
    category: 'Salon & Spa',
    description: 'Sleek dark-themed website with appointment booking, stylist profiles, and service pricing.',
    tags: ['React', 'GSAP', 'Booking System'],
    image: 'noir_elite_3d_1779609143469.jpg',
    result: 'Fully Booked in Week 1',
    accent: '#7c3aed',
    liveUrl: '#',
  },
  {
    id: 'p3',
    title: 'Sanjai Estates',
    category: 'Real Estate',
    description: 'Property listing platform with search filters, virtual tour links, and lead capture forms.',
    tags: ['Next.js', 'Tailwind', 'PostgreSQL'],
    image: 'sanjai_estates_3d_1779609159297.jpg',
    result: '3x More Enquiries',
    accent: '#00e5ff',
    liveUrl: '#',
  },
  {
    id: 'p4',
    title: 'Vilas Salon',
    category: 'Beauty Salon',
    description: 'Elegant website with service menu, before/after gallery, and WhatsApp booking integration.',
    tags: ['React', 'Framer Motion', 'WhatsApp API'],
    image: 'vilas_salon_3d_1779609174443.jpg',
    result: '2x Appointments',
    accent: '#ff6b6b',
    liveUrl: '#',
  },
  {
    id: 'p5',
    title: 'Aurelie Bistro',
    category: 'Café & Bistro',
    description: 'Premium café website with digital menu, Instagram feed integration, and loyalty program page.',
    tags: ['React', 'Tailwind', 'Instagram API'],
    image: 'aurelie_bistro_3d_1779609193458.jpg',
    result: '+60% Online Orders',
    accent: '#39ff14',
    liveUrl: '#',
  },
  {
    id: 'p6',
    title: 'Velora Coffee',
    category: 'Coffee Shop',
    description: 'Warm, inviting website with online menu, store locator, and a subscription sign-up page.',
    tags: ['React', 'GSAP', 'Tailwind'],
    image: 'velora_coffee_3d_1779609208836.jpg',
    result: '500+ Subscribers',
    accent: '#7c3aed',
    liveUrl: '#',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Ramesh Kumar',
    business: 'Ramesh Catering Services',
    location: 'Salem, TN',
    text: 'Sanjai built our website in just 5 days. Our phone hasn\'t stopped ringing since. Best investment we made for our business.',
    rating: 5,
    initials: 'RK',
    color: '#00e5ff',
  },
  {
    name: 'Priya Sharma',
    business: 'Priya Beauty Studio',
    location: 'Coimbatore, TN',
    text: 'Very professional work. The website looks exactly how I imagined — clean, beautiful, and my clients love it. Highly recommend!',
    rating: 5,
    initials: 'PS',
    color: '#7c3aed',
  },
  {
    name: 'Arun Vijay',
    business: 'AV Properties',
    location: 'Chennai, TN',
    text: 'Sanjai understood our requirement quickly and delivered beyond expectations. We started getting enquiries within the first week.',
    rating: 5,
    initials: 'AV',
    color: '#39ff14',
  },
  {
    name: 'Meena Krishnan',
    business: 'Meena\'s Café',
    location: 'Trichy, TN',
    text: 'Affordable price, fast delivery, and great quality. Sanjai was always available to answer my questions. 10/10!',
    rating: 5,
    initials: 'MK',
    color: '#ff6b6b',
  },
];

export const WHY_ME = [
  {
    icon: 'Zap',
    title: 'Fast Delivery',
    description: 'Most websites are ready in 5–7 days. I work fast without cutting corners on quality.',
    accent: '#00e5ff',
  },
  {
    icon: 'Star',
    title: 'Premium Design',
    description: 'Every website is custom-designed — not a template. Your business deserves to stand out.',
    accent: '#7c3aed',
  },
  {
    icon: 'Shield',
    title: 'Ongoing Support',
    description: 'After launch, I\'m still here. Updates, fixes, and changes — all handled quickly.',
    accent: '#39ff14',
  },
  {
    icon: 'Smartphone',
    title: 'Mobile First',
    description: 'Over 80% of your customers browse on phones. Every site I build is perfect on all screens.',
    accent: '#ff6b6b',
  },
];
